spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dormitory?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 100
      idle-timeout: 30000
      validation-timeout: 250
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    static-path-pattern: /static/**               #静态资源访问路径
  resources:
    static-locations: classpath:/static/          #静态资源映射路径
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: LEGACYHTML5
    prefix: classpath:/static/layuimini/
    suffix: .html
server:
  port: 8080
